theme: jekyll-theme-hacker
title: SaMaCraft Regelwerk
description: Offizielle Regeln, Team-Infos und Änderungen des SaMaCraft Minecraft-Servers.
show_downloads: false
github:
  is_project_page: false
